### Accessing/Changing specific elements, rows, columns, etc

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],
 [8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

In [ ]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:,3]


array([ 4, 11])

In [ ]:
# something fancy [startindex:endindex:stepsize]

a = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])

a[0, 1:-1: 3]

array([2, 5])

In [ ]:
a[0,5] = 20

#: means select all rows, 2 means select column 2 across all rows
a[:,2] = [1,2]
print(a)


[[ 1  2  1  4  5 20  7]
 [ 8  9  2 11 12 13 14]]


In [ ]:
a = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14],
              [15,16,17,18,19,20,21]])
a[1 :,2] = [22] # select row 1 and 2 and in column 2 replace values with 22
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 22 11 12 13 14]
 [15 16 22 18 19 20 21]]


# 3D example

In [ ]:
b = np.array([[[1,2],[3,4]],  [[5,6],[7,8]]]) #shape (2,2,2)
print(b)

NameError: name 'np' is not defined

In [ ]:
# Get specific element # block, row, element(column)
b[0,1,0]

3

In [ ]:
# replace : select all blocks, 1 select second row of each block, : all elements in the second row
b[:,0,:] =[[9,9],[8,8]]
print(b)

[[[9 9]
  [3 4]]

 [[8 8]
  [7 8]]]


### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3),)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number (full Return a new array of given shape and type, filled with fill_value.)
import numpy as np
np.full((2,2), [0,99])

array([[ 0, 99],
       [ 0, 99]])

In [ ]:
# Random decimal numbers between 0 and 1, try two arguments, first will give you an error and then do it with tuple
np.random.random(6)

array([0.86866521, 0.08102415, 0.42503109, 0.34238033, 0.32093907,
       0.57530535])

In [ ]:
#Random Integer values
#low: The inclusive lower bound of the random integers.
#high: The exclusive upper bound of the random integers (if None, it will be assumed to be equal to low, and the result will be 0).
#size: The shape of the output array.

np.random.randint(-4,2 , size=(3,2))

array([[-3,  0],
       [ 1, -4],
       [-3,  0]])

An identity matrix is a square matrix where:
The diagonal elements are 1.
All off-diagonal elements are 0.

In [ ]:
# The identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

a: The input array that you want to repeat elements from.
repeats: The number of times each element (or block of elements) should be repeated.
axis: The axis along which to repeat the values. If None, the array is flattened before repeating.

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In this case, the values within each row are repeated 3 times, so we get 9 values in total, expanding horizontally.

In [ ]:
arr = np.array([[1, 2, 3]])
r2 = np.repeat(arr, 3, axis=1)
print(r2)


[[1 1 1 2 2 2 3 3 3]]


Example 3: Repeating Elements Without Axis (axis=None)
If axis is not specified, or set to None, the array is flattened, and then elements are repeated across the entire array.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
r3 = np.repeat(arr, 2, axis=1)
print(r3)


[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
r4 = np.repeat(arr, 2, axis=0)
print(r4)


[[1 2]
 [1 2]
 [3 4]
 [3 4]
 [5 6]
 [5 6]]


##### Be careful when copying arrays!!!

In [ ]:
#shallow copy
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [ ]:
#deep copy
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a*b)

[ 5 12 21 32]
