# Numpy

In [ ]:
list1 = [1,2,3]
list2 = [2,4,5]
print(list1+list2)

[1, 2, 3, 2, 4, 5]


In [ ]:
list1 = [1,2,3]
list2 = [2,4,5,4]
results = []
results.append(list1[0] + list2[0])
results.append(list1[1] + list2[1])
results.append(list1[2] + list2[2])
print(results)

[3, 6, 8]


In [ ]:
list1 = [1, 2, 3]
list2 = [2, 4, 5]

# Initialize an empty list to store the results
result = []

# Use a simple for loop for element-wise addition
for i in range(len(list1)):
    result.append(list1[i] + list2[i])

print(result)  # Output: [3, 6, 8]


[3, 6, 8]


In [ ]:
#alias(like a nickname)
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
a = np.array([1,2,3])
print(a+a)

[2 4 6]


In [ ]:
import time
list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()
result = []
for i in range(len(list1)):
    result.append(list1[i] + list2[i])
end = time.time()
print("loop addition time:", end - start)

# Adding with NumPy
array1 = np.array(list1)
array2 = np.array(list2)

start = time.time()
result = array1 + array2
end = time.time()
print("loop addition time:", end - start)




loop addition time: 0.3145484924316406
loop addition time: 0.0023033618927001953


In [ ]:
def print_array_details(a):
  print(f"Dimensions: {a.ndim}\nshape: {a.shape}\ndtype: {a.dtype}")

a = np.array([1,2,3,4,5,6,7,8])
print(a)
print_array_details(a)

[1 2 3 4 5 6 7 8]
Dimensions: 1
shape: (8,)
dtype: int64


In [ ]:
a2 = a.reshape([2,4])
print(a2)
print(a2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
#Then a 3d array from our 1d array
a = np.array([1,2,3,4,5,6,7,8])
a3 = a.reshape([2,2,2])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9, 10,11,12])
a4 = a.reshape([2,3,2])
print(a4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
zeros_array = np.zeros([2, 3])
print(type(zeros_array))   # <class 'numpy.ndarray'>
print(zeros_array.dtype)

<class 'numpy.ndarray'>
float64


In [ ]:
print(np.ones([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.empty([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
print(np.empty([3,3]))

[[4.87796773e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
print(np.random.random((2,2)))
print(np.linspace(2,11,5)) # five numbers range 2-10
print(np.arange(2,10,2)) # 2 being the step size

[[0.6093875  0.24693459]
 [0.9706154  0.38462575]]
[ 2.    4.25  6.5   8.75 11.  ]
[2 4 6 8]


In [ ]:
a = np.array((1,2,3,4,5,6,7,8))
print(a[-2])
print(a[3:7]) # a slice

7
[4 5 6 7]


In [ ]:
print(a*2)
print(a/2)

[ 2  4  6  8 10 12 14 16]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
